[platformio]
default_envs = usb

; Faelles for alle miljoer
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
    adafruit/Adafruit SHT4x Library@^1.0.5

; Upload via USB kabel
[env:usb]

; Upload over WiFi (ArduinoOTA)
; Koden hentes fra miljoevariablen OTA_PASS, saa den ikke ligger i repoet
[env:ota]
upload_protocol = espota
upload_port = drivhus.local
upload_flags =
    --auth=${sysenv.OTA_PASS}